### PR TITLE
Added endpoint to get all tags

### PR DESCRIPTION
**Pull request by ra-ver**
Created a new endpoint to fetch a unique list of all interests/tags from interests of all the users. 

Example API call to get all Tags:
```bash
query q {
	tags{values}
}
```

Example response:
```bash
{
	"data": {
		"tags": {
			"values": [
				"body cancer",
				"nose cancer",
				"head cancer",
				"toe cancer"
			]
		}
	}
}
```

* PS:
Since tags/interest exist as a field for each User and this query is just collating unique value of that field; we decided not to expose any endpoints to delete/update tags separately. That should be done using delete/update endpoints related to User.

### CODE REVIEW

**Comment by Jephuff** [comment]
Where are the possible values of interests coming from? It looks like the frontend it's not free text?

**Comment by cy** [comment]
yeah @ra-ver wants to get his hands dirty with react and add free-text to the front end

**Comment by Jephuff** [comment]
I imagine we will need to get counts for each tag so might be a good idea to update this to something like 
```
tags {
  count
  items {
    value
    total
  }
}
```

```
{
  "data": {
    "tags": {
      "count": 1,
      "items": [
        {
          "value": "tag value",
          "total": total users with tag
        }
      ]
    }
  }
}
```

also, seeing as the number of tags isn't really limited, adding the parameters that users has would probably be a good idea.

**Comment by jgnieuwhof** [comment]
closing this PR & opening another since this is technically coming from me now

**Pull request closed without merging**
